version: 0.2
phases:
  pre_build:
    commands:
      - echo Beta dotnetcore build started on `date`...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 328765353998.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=328765353998.dkr.ecr.us-east-2.amazonaws.com/foundant/glm-beta-dotnetcore
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)      
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $COMMIT_HASH
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd v2
      - docker build -t $REPOSITORY_URI:latest . -f src/api/Dockerfile
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"dotnetcore-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json