version: 0.2
phases:
  pre_build:
    commands:
      - echo Beta dotnetcore build started on `date`...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 328765353998.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=328765353998.dkr.ecr.us-east-2.amazonaws.com/foundant/glm-beta-dotnetcore
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)      
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $COMMIT_HASH
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files: imagedefinitions.json